behaviors:
  PlayerTest:
    trainer_type: sac
    hyperparameters:
      init_entcoef: 0.9
      save_replay_buffer: true
      steps_per_update: 5
# common
      batch_size: 64
      buffer_size: 50000
      learning_rate: 3.0e-4
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 1000000
    time_horizon: 1000
    summary_freq: 10000